### ISSUE TITLE
当点击设置中的重置时，并没有重置回Momotalk主题默认设置，而是回到了QQ默认设置

### ISSUE THREAD

**Issue by himetuki** [MiyakoDevelopTeam/MomoTalkNTQQ-Theme#1]
当点击设置中的重置时，并没有重置回Momotalk主题默认设置，而是回到了QQ默认设置

**Comment by OnikayokoMaVie** [comment]
你好，非常感谢你的Issue提交。由于我的学业原因，很长时间没有看GitHub，所以在此说一声对不起！

我已经解决了你所说的问题并发布了新的Release：Beta 1.0.2，主要改动是修改了 setting.json 中的 defaultValue。

我认为你需要把新版本的 setting.json （MomoTalkNTQQ-Theme-4\src\setting.json）复制到插件的数据目录中覆盖掉 [LiteloaderNTQQ数据目录]\momotalk_theme\setting.json

注：LiteloaderNTQQ数据目录可以在LiteloaderNTQQ主页中找到，位置在 目录 > 数据目录，按旁边的"进入目录"按钮即可。

除此之外，你可能会遇到背景纯白的问题，你可以通过以下方法来自行修复：
1. MomotalkNTQQ 主题 > 壁纸设定 > 选择壁纸，按"选择图片"，定位到 [LiteloaderNTQQ本体目录]\plugins\MomotalkNTQQ-Theme\image\light.jpg，本体目录的寻找方式和数据目录同理。
2. MomotalkNTQQ 主题 > 壁纸设定 > 背景色，设置R，G，B为：255,247,226
